### PR TITLE
support for node-20

### LINKED ISSUE #43: Deprecation warning due to Node 16
Node 16 is [now deprecated](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/). Because of this, when using this action, you'll see warnings.

Please update the action to Node 20.

### PR DESCRIPTION
**Pull request by v1v**
Closes https://github.com/phoenix-actions/test-reporting/issues/43

This is a breaking change, see https://github.com/hashicorp/vault-action/issues/526

### CODE REVIEW

**Comment by tonit** [comment]
would love to have this merged

**Comment by saurabh-gadariya** [comment]
Can you please merge this ASAP
node 16 warning is so stressful!

**Review by saurabh-gadariya — APPROVED** [review]

**Review by JakeTowers — APPROVED** [review]

**Comment by JakeTowers** [comment]
@IanMoroney not sure why the build is failing on this, I opened a new branch with the exact same changes and the build succeeds...

I thought it was to do with GitHub permissions needed as it seems to fail here - https://github.com/phoenix-actions/test-reporting/blob/main/src/main.ts#L186-L195 and that says it needs the `checks: write` permissions, but I've had no luck

**Comment by IanMoroney** [comment]
there is a permission now required @JakeTowers in the ci workflow.

```
permission:
  checks: write
```

**Comment by IanMoroney** [comment]
committed the required change to main

**Comment by IanMoroney** [comment]
Tested successfully in #47 . Merged to main, so will close the PR in favour of that one with successful CI builds

**Pull request closed without merging**
