### PR TITLE
feat: add output to step summary

### PR DESCRIPTION
**Pull request by jcdickinson**
This PR allows adds the option `output-to`, which can be set to `step-summary` (or `checks`). This circumvents the issue mentioned in the README under "Github limitations"

### CODE REVIEW

**Comment by maxbirkner** [comment]
Thanks for fixing this critical bug of this otherwise great action! Used both options and they worked as expected.

**Comment by pleonowens** [comment]
Can we merge please? We could use this

**Comment by maxbirkner** [comment]
> Can we merge please? We could use this


You can use it in your workflow already like this:
`uses: phoenix-actions/test-reporting@f68b7c5fcffefd98dd230c686cca6c26683668c3`

**Comment by Piedone** [comment]
Checked this out. Works well:

image

It's also worth noting unlike with separate reports, updating the workflow summary doesn't need write access to the repo, and thus will also work if you open a PR from a fork, like [here](https://github.com/OrchardCMS/OrchardCore/actions/runs/3422132621).

**Comment by IanMoroney** [comment]
Great improvement @jcdickinson!
Merged 👍

**Comment by IanMoroney** [comment]
https://github.com/phoenix-actions/test-reporting/releases/tag/v9

**Pull request merged**
